name: Bug
description: I have an error/something is not working as expected/etc.
labels:
  - bug
body:
  - type: input
    id: package_name
    attributes:
      label: Package name
      description: Specify the package name.
    validations:
      required: true

  - type: input
    id: package_version
    attributes:
      label: Package version
      description: Specify the package version.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your issue.
    validations:
      required: true
