name: Build pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build releases]
    types: [completed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write

env:
  BUILD_DIR: '_pages'

jobs:
  build_pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: |
          python -m pip install packaging jinja2

      - name: Build pages
        run: |
          python .scripts/build-pages.py --repo ${{ github.repository }} --build_dir ${{ env.BUILD_DIR }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy_pages:
    runs-on: ubuntu-latest
    needs: build_pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
