name: Sanity checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths: [subprojects/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  sanity_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: |
          python -m pip install packaging meson

      - name: Perform sanity checks
        run: |
          python .scripts/check.py
